// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class AutoReplies
    {
        public AutoReplies()
        {
            AutoReplyKeyWords = new HashSet<AutoReplyKeyWords>();
            ChatRoomAutoReplies = new HashSet<ChatRoomAutoReplies>();
        }

        public int Id { get; set; }
        public string AutoReplyContent { get; set; }

        public virtual ICollection<AutoReplyKeyWords> AutoReplyKeyWords { get; set; }
        public virtual ICollection<ChatRoomAutoReplies> ChatRoomAutoReplies { get; set; }
    }
}