// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class Brands
    {
        public Brands()
        {
            Products = new HashSet<Products>();
        }

        public int Id { get; set; }
        public string Brand { get; set; }
        public string BrandImageUrl { get; set; }
        public string BrandIntroduce { get; set; }
        public int OnSaleId { get; set; }

        public virtual OnSale OnSale { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}