// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class Categories
    {
        public Categories()
        {
            ContestCategory = new HashSet<ContestCategory>();
        }

        public int Id { get; set; }
        public string Category { get; set; }
        public int Distance { get; set; }

        public virtual ICollection<ContestCategory> ContestCategory { get; set; }
    }
}