// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class ChatRoomAutoReplies
    {
        public int Id { get; set; }
        public DateTime SentTime { get; set; }
        public int AutoReplyId { get; set; }
        public int ChatRoomId { get; set; }

        public virtual AutoReplies AutoReply { get; set; }
        public virtual ChatRooms ChatRoom { get; set; }
    }
}