// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class Contests
    {
        public Contests()
        {
            ContestCategory = new HashSet<ContestCategory>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int SupplierId { get; set; }
        public DateTime CreateDateTime { get; set; }
        public DateTime ContestDate { get; set; }
        public DateTime RegistrationDeadline { get; set; }
        public string Area { get; set; }
        public string Location { get; set; }
        public string MapUrl { get; set; }
        public string RegistrationUrl { get; set; }
        public string Detail { get; set; }
        public bool Review { get; set; }

        public virtual Suppliers Supplier { get; set; }
        public virtual ICollection<ContestCategory> ContestCategory { get; set; }
    }
}