// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class Coupons
    {
        public Coupons()
        {
            MembersCoupons = new HashSet<MembersCoupons>();
            Orders = new HashSet<Orders>();
        }

        public int Id { get; set; }
        public string CouponName { get; set; }
        public string CouponNumber { get; set; }
        public int CouponType { get; set; }
        public int CouponDiscount { get; set; }
        public int? CouponQuantity { get; set; }
        public int? AccountQuantity { get; set; }
        public int? MinSpend { get; set; }
        public bool? IsCombine { get; set; }
        public string CouponImage { get; set; }
        public string CouponContent { get; set; }
        public DateTime? StartAt { get; set; }
        public DateTime? EndAt { get; set; }
        public int? CorrespondProduct { get; set; }
        public DateTime? CreateAt { get; set; }
        public bool? SoftDelete { get; set; }

        public virtual ICollection<MembersCoupons> MembersCoupons { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}