// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class CustomerFeedbacks
    {
        public int Id { get; set; }
        public string FeedbackContent { get; set; }
        public string CustomerName { get; set; }
        public string Email { get; set; }
        public int QuestionTypeId { get; set; }
        public int Status { get; set; }
        public DateTime CreateTime { get; set; }

        public virtual QuestionTypes QuestionType { get; set; }
    }
}