// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class ForumSectionBranch1TopicsThread
    {
        public int Id { get; set; }
        public int TopicId { get; set; }
        public int TopicState { get; set; }
        public int ReplyNumber { get; set; }
        public string ReplyContent { get; set; }
        public DateTime ReplyTime { get; set; }
        public int ReplyState { get; set; }
        public int ReplyMemberId { get; set; }

        public virtual Members ReplyMember { get; set; }
        public virtual ForumSectionBranch1Topics Topic { get; set; }
    }
}