// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class ForumSectionBranch1Topics
    {
        public ForumSectionBranch1Topics()
        {
            ForumSectionBranch1TopicsThread = new HashSet<ForumSectionBranch1TopicsThread>();
        }

        public int Id { get; set; }
        public int BranchId { get; set; }
        public string Topic { get; set; }
        public int State { get; set; }

        public virtual ForumSectionBranches Branch { get; set; }
        public virtual ICollection<ForumSectionBranch1TopicsThread> ForumSectionBranch1TopicsThread { get; set; }
    }
}