// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class Members
    {
        public Members()
        {
            CartItems = new HashSet<CartItems>();
            ForumSectionBranch1TopicsThread = new HashSet<ForumSectionBranch1TopicsThread>();
            ForumSectionBranches = new HashSet<ForumSectionBranches>();
            MembersCoupons = new HashSet<MembersCoupons>();
            Orders = new HashSet<Orders>();
        }

        public int MemberId { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public bool Subscription { get; set; }
        public bool IsConfirmed { get; set; }
        public bool Freeze { get; set; }
        public int State { get; set; }

        public virtual ICollection<CartItems> CartItems { get; set; }
        public virtual ICollection<ForumSectionBranch1TopicsThread> ForumSectionBranch1TopicsThread { get; set; }
        public virtual ICollection<ForumSectionBranches> ForumSectionBranches { get; set; }
        public virtual ICollection<MembersCoupons> MembersCoupons { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}