// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class MembersCoupons
    {
        public int MemberId { get; set; }
        public int CouponId { get; set; }
        public int CouponsQuantity { get; set; }

        public virtual Coupons Coupon { get; set; }
        public virtual Members Member { get; set; }
    }
}