// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class Orders
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public string OrderNumber { get; set; }
        public DateTime? CreateAt { get; set; }
        public int OrderType { get; set; }
        public int OrderStatus { get; set; }
        public int TradeStatus { get; set; }
        public int? UseCoupon { get; set; }
        public int Amount { get; set; }
        public string ShippingMethod { get; set; }
        public string OrderAddress { get; set; }
        public string OrderContent { get; set; }

        public virtual Members Member { get; set; }
        public virtual Coupons UseCouponNavigation { get; set; }
    }
}