// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class ProductsImages
    {
        public int Id { get; set; }
        public string ImageUrl { get; set; }
    }
}