// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class QuestionTypes
    {
        public QuestionTypes()
        {
            CommonQuestions = new HashSet<CommonQuestions>();
            CustomerFeedbacks = new HashSet<CustomerFeedbacks>();
        }

        public int Id { get; set; }
        public string QuestionType { get; set; }

        public virtual ICollection<CommonQuestions> CommonQuestions { get; set; }
        public virtual ICollection<CustomerFeedbacks> CustomerFeedbacks { get; set; }
    }
}