// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class QuickReplyKeyWords
    {
        public int Id { get; set; }
        public int QuickReplyId { get; set; }
        public string KeyWord { get; set; }

        public virtual QuickReplies QuickReply { get; set; }
    }
}