// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class Registration
    {
        public Registration()
        {
            RegistrationInformation = new HashSet<RegistrationInformation>();
        }

        public int Id { get; set; }
        public int MemberId { get; set; }
        public int ContestCategoryId { get; set; }
        public bool PaymentStatus { get; set; }

        public virtual ContestCategory ContestCategory { get; set; }
        public virtual ICollection<RegistrationInformation> RegistrationInformation { get; set; }
    }
}