// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class RegistrationInformation
    {
        public int Id { get; set; }
        public int RegistrationId { get; set; }
        public int InformationId { get; set; }

        public virtual Information Information { get; set; }
        public virtual Registration Registration { get; set; }
    }
}