// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class Stocks
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int ProductSizeId { get; set; }
        public int Stock { get; set; }

        public virtual Products Product { get; set; }
        public virtual ProductSize ProductSize { get; set; }
    }
}