// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using The_fifth_group_FinalAPI.DTOs;

namespace The_fifth_group_FinalAPI.Models
{
    public partial class TheFifthGroupOfTopicsContext : DbContext
    {
        public TheFifthGroupOfTopicsContext()
        {
        }

        public TheFifthGroupOfTopicsContext(DbContextOptions<TheFifthGroupOfTopicsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AutoReplies> AutoReplies { get; set; }
        public virtual DbSet<AutoReplyKeyWords> AutoReplyKeyWords { get; set; }
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<CartItems> CartItems { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<ChatContents> ChatContents { get; set; }
        public virtual DbSet<ChatRoomAutoReplies> ChatRoomAutoReplies { get; set; }
        public virtual DbSet<ChatRooms> ChatRooms { get; set; }
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<CommonAnswers> CommonAnswers { get; set; }
        public virtual DbSet<CommonQuestions> CommonQuestions { get; set; }
        public virtual DbSet<ContestCategory> ContestCategory { get; set; }
        public virtual DbSet<Contests> Contests { get; set; }
        public virtual DbSet<Coupons> Coupons { get; set; }
        public virtual DbSet<CustomerFeedbacks> CustomerFeedbacks { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<ForumSection> ForumSection { get; set; }
        public virtual DbSet<ForumSectionBranch1Topics> ForumSectionBranch1Topics { get; set; }
        public virtual DbSet<ForumSectionBranch1TopicsThread> ForumSectionBranch1TopicsThread { get; set; }
        public virtual DbSet<ForumSectionBranches> ForumSectionBranches { get; set; }
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<MembersCoupons> MembersCoupons { get; set; }
        public virtual DbSet<OnSale> OnSale { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<ProductSize> ProductSize { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductsImages> ProductsImages { get; set; }
        public virtual DbSet<QuestionTypes> QuestionTypes { get; set; }
        public virtual DbSet<QuickReplies> QuickReplies { get; set; }
        public virtual DbSet<QuickReplyKeyWords> QuickReplyKeyWords { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<RegistrationInformation> RegistrationInformation { get; set; }
        public virtual DbSet<Stocks> Stocks { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AutoReplies>(entity =>
            {
                entity.Property(e => e.AutoReplyContent)
                    .IsRequired()
                    .HasMaxLength(1000);
            });

            modelBuilder.Entity<AutoReplyKeyWords>(entity =>
            {
                entity.Property(e => e.AutoReplyId).HasColumnName("AutoReplyID");

                entity.Property(e => e.KeyWord)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.HasOne(d => d.AutoReply)
                    .WithMany(p => p.AutoReplyKeyWords)
                    .HasForeignKey(d => d.AutoReplyId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_AutoReplyKeyWords_AutoReplies");
            });

            modelBuilder.Entity<Brands>(entity =>
            {
                entity.Property(e => e.Brand)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.BrandImageUrl)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.BrandIntroduce)
                    .IsRequired()
                    .HasMaxLength(350);

                entity.Property(e => e.OnSaleId).HasColumnName("OnSale_Id");

                entity.HasOne(d => d.OnSale)
                    .WithMany(p => p.Brands)
                    .HasForeignKey(d => d.OnSaleId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Brands_OnSale");
            });

            modelBuilder.Entity<CartItems>(entity =>
            {
                entity.Property(e => e.MemberId).HasColumnName("Member_Id");

                entity.Property(e => e.ProductId).HasColumnName("Product_Id");

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.CartItems)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CartItems_Members");

                entity.HasOne(d => d.Product)
                    .WithMany(p => p.CartItems)
                    .HasForeignKey(d => d.ProductId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CartItems_Products");
            });

            modelBuilder.Entity<Categories>(entity =>
            {
                entity.Property(e => e.Category)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<ChatContents>(entity =>
            {
                entity.Property(e => e.ChatContent)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.SentTime).HasColumnType("datetime");

                entity.HasOne(d => d.ChatRoom)
                    .WithMany(p => p.ChatContents)
                    .HasForeignKey(d => d.ChatRoomId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ChatContents_ChatRooms");

                entity.HasOne(d => d.Employee)
                    .WithMany(p => p.ChatContents)
                    .HasForeignKey(d => d.EmployeeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ChatContents_Employees");
            });

            modelBuilder.Entity<ChatRoomAutoReplies>(entity =>
            {
                entity.Property(e => e.SentTime).HasColumnType("datetime");

                entity.HasOne(d => d.AutoReply)
                    .WithMany(p => p.ChatRoomAutoReplies)
                    .HasForeignKey(d => d.AutoReplyId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ChatRoomAutoReplies_AutoReplies");

                entity.HasOne(d => d.ChatRoom)
                    .WithMany(p => p.ChatRoomAutoReplies)
                    .HasForeignKey(d => d.ChatRoomId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ChatRoomAutoReplies_ChatRooms");
            });

            modelBuilder.Entity<ChatRooms>(entity =>
            {
                entity.Property(e => e.EndTime).HasColumnType("datetime");

                entity.Property(e => e.StartTime).HasColumnType("datetime");
            });

            modelBuilder.Entity<Colors>(entity =>
            {
                entity.Property(e => e.Color)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<CommonAnswers>(entity =>
            {
                entity.Property(e => e.Answer)
                    .IsRequired()
                    .HasMaxLength(1000);

                entity.HasOne(d => d.CommonQuestion)
                    .WithMany(p => p.CommonAnswers)
                    .HasForeignKey(d => d.CommonQuestionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CommonAnswer_CommonQuestion");
            });

            modelBuilder.Entity<CommonQuestions>(entity =>
            {
                entity.Property(e => e.Question)
                    .IsRequired()
                    .HasMaxLength(1000);

                entity.HasOne(d => d.QuestionType)
                    .WithMany(p => p.CommonQuestions)
                    .HasForeignKey(d => d.QuestionTypeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CommonQuestions_QuestionTypes");
            });

            modelBuilder.Entity<ContestCategory>(entity =>
            {
                entity.ToTable("Contest_Category");

                entity.Property(e => e.CategoryId).HasColumnName("CategoryID");

                entity.Property(e => e.ContestId).HasColumnName("ContestID");

                entity.HasOne(d => d.Category)
                    .WithMany(p => p.ContestCategory)
                    .HasForeignKey(d => d.CategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Contest_Category_Category");

                entity.HasOne(d => d.Contest)
                    .WithMany(p => p.ContestCategory)
                    .HasForeignKey(d => d.ContestId)
                    .HasConstraintName("FK_Contest_Category_Contest");
            });

            modelBuilder.Entity<Contests>(entity =>
            {
                entity.Property(e => e.Area)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.ContestDate).HasColumnType("datetime");

                entity.Property(e => e.CreateDateTime).HasColumnType("datetime");

                entity.Property(e => e.Detail).IsRequired();

                entity.Property(e => e.Location)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.MapUrl)
                    .IsRequired()
                    .HasColumnName("MapURL");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.RegistrationDeadline).HasColumnType("datetime");

                entity.Property(e => e.RegistrationUrl)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("RegistrationURL");

                entity.Property(e => e.SupplierId).HasColumnName("SupplierID");

                entity.HasOne(d => d.Supplier)
                    .WithMany(p => p.Contests)
                    .HasForeignKey(d => d.SupplierId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Contests_Suppliers");
            });

            modelBuilder.Entity<Coupons>(entity =>
            {
                entity.Property(e => e.CouponContent).HasMaxLength(500);

                entity.Property(e => e.CouponImage).HasMaxLength(50);

                entity.Property(e => e.CouponName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.CouponNumber)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CreateAt)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.EndAt).HasColumnType("datetime");

                entity.Property(e => e.IsCombine).HasDefaultValueSql("((0))");

                entity.Property(e => e.SoftDelete).HasDefaultValueSql("((0))");

                entity.Property(e => e.StartAt).HasColumnType("datetime");
            });

            modelBuilder.Entity<CustomerFeedbacks>(entity =>
            {
                entity.Property(e => e.CreateTime).HasColumnType("datetime");

                entity.Property(e => e.CustomerName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(256);

                entity.Property(e => e.FeedbackContent)
                    .IsRequired()
                    .HasMaxLength(1000);

                entity.Property(e => e.Status).HasDefaultValueSql("((1))");

                entity.HasOne(d => d.QuestionType)
                    .WithMany(p => p.CustomerFeedbacks)
                    .HasForeignKey(d => d.QuestionTypeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CustomerFeedbacks_QuestionTypes");
            });

            modelBuilder.Entity<Employees>(entity =>
            {
                entity.Property(e => e.Account)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Address).HasMaxLength(60);

                entity.Property(e => e.Email).HasMaxLength(200);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Permission).HasDefaultValueSql("((5))");

                entity.Property(e => e.Title).HasMaxLength(30);
            });

            modelBuilder.Entity<ForumSection>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.SectionName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("sectionName");
            });

            modelBuilder.Entity<ForumSectionBranch1Topics>(entity =>
            {
                entity.ToTable("Forum_SectionBranch1Topics");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Topic)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.HasOne(d => d.Branch)
                    .WithMany(p => p.ForumSectionBranch1Topics)
                    .HasForeignKey(d => d.BranchId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Forum_SectionBranch1Topics_ForumSectionBranches");
            });

            modelBuilder.Entity<ForumSectionBranch1TopicsThread>(entity =>
            {
                entity.ToTable("Forum_SectionBranch1TopicsThread");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.ReplyContent)
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnName("replyContent");

                entity.Property(e => e.ReplyMemberId).HasColumnName("replyMemberId");

                entity.Property(e => e.ReplyNumber).HasColumnName("replyNumber");

                entity.Property(e => e.ReplyState).HasColumnName("replyState");

                entity.Property(e => e.ReplyTime)
                    .HasColumnType("datetime")
                    .HasColumnName("replyTime");

                entity.Property(e => e.TopicId).HasColumnName("topicId");

                entity.Property(e => e.TopicState).HasColumnName("topicState");

                entity.HasOne(d => d.ReplyMember)
                    .WithMany(p => p.ForumSectionBranch1TopicsThread)
                    .HasForeignKey(d => d.ReplyMemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Forum_SectionBranch1TopicsThread_Members");

                entity.HasOne(d => d.Topic)
                    .WithMany(p => p.ForumSectionBranch1TopicsThread)
                    .HasForeignKey(d => d.TopicId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Forum_SectionBranch1TopicsThread_Forum_SectionBranch1Topics");
            });

            modelBuilder.Entity<ForumSectionBranches>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.AdministratorId).HasColumnName("administratorId");

                entity.Property(e => e.BranchName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("branchName");

                entity.Property(e => e.SectionAdministrator)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("sectionAdministrator");

                entity.Property(e => e.SectionNameId).HasColumnName("sectionNameId");

                entity.HasOne(d => d.Administrator)
                    .WithMany(p => p.ForumSectionBranches)
                    .HasForeignKey(d => d.AdministratorId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ForumSectionBranches_Members");

                entity.HasOne(d => d.SectionName)
                    .WithMany(p => p.ForumSectionBranches)
                    .HasForeignKey(d => d.SectionNameId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ForumSectionBranches_ForumSection");
            });

            modelBuilder.Entity<Information>(entity =>
            {
                entity.Property(e => e.Address)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Phone)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength();
            });

            modelBuilder.Entity<Members>(entity =>
            {
                entity.HasKey(e => e.MemberId)
                    .HasName("PK_finalMembers");

                entity.Property(e => e.MemberId).HasColumnName("Member_Id");

                entity.Property(e => e.Account)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Mail)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Phone)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .IsFixedLength();
            });

            modelBuilder.Entity<MembersCoupons>(entity =>
            {
                entity.HasKey(e => new { e.MemberId, e.CouponId });

                entity.ToTable("Members_Coupons");

                entity.HasOne(d => d.Coupon)
                    .WithMany(p => p.MembersCoupons)
                    .HasForeignKey(d => d.CouponId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Members_Coupons_Coupons");

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.MembersCoupons)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Members_Coupons_Members");
            });

            modelBuilder.Entity<OnSale>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();
            });

            modelBuilder.Entity<Orders>(entity =>
            {
                entity.Property(e => e.CreateAt)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.OrderAddress).HasMaxLength(200);

                entity.Property(e => e.OrderContent)
                    .IsRequired()
                    .HasMaxLength(500);

                entity.Property(e => e.OrderNumber)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ShippingMethod).HasMaxLength(50);

                entity.HasOne(d => d.Member)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.MemberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Orders_Members");

                entity.HasOne(d => d.UseCouponNavigation)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.UseCoupon)
                    .HasConstraintName("FK_Orders_Coupons");
            });

            modelBuilder.Entity<ProductSize>(entity =>
            {
                entity.Property(e => e.Size)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<Products>(entity =>
            {
                entity.Property(e => e.BrandId).HasColumnName("Brand_Id");

                entity.Property(e => e.ColorId).HasColumnName("Color_Id");

                entity.Property(e => e.ImageUrl)
                    .IsRequired()
                    .HasMaxLength(300);

                entity.Property(e => e.ProductIntroduce)
                    .IsRequired()
                    .HasMaxLength(500);

                entity.Property(e => e.ProductName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.HasOne(d => d.Brand)
                    .WithMany(p => p.Products)
                    .HasForeignKey(d => d.BrandId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Products_Brands");

                entity.HasOne(d => d.Color)
                    .WithMany(p => p.Products)
                    .HasForeignKey(d => d.ColorId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Products_Colors");
            });

            modelBuilder.Entity<ProductsImages>(entity =>
            {
                entity.Property(e => e.ImageUrl)
                    .IsRequired()
                    .HasMaxLength(300);
            });

            modelBuilder.Entity<QuestionTypes>(entity =>
            {
                entity.Property(e => e.QuestionType)
                    .IsRequired()
                    .HasMaxLength(256);
            });

            modelBuilder.Entity<QuickReplies>(entity =>
            {
                entity.Property(e => e.QuickReplyContent)
                    .IsRequired()
                    .HasMaxLength(1000);
            });

            modelBuilder.Entity<QuickReplyKeyWords>(entity =>
            {
                entity.Property(e => e.KeyWord)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.QuickReplyId).HasColumnName("QuickReplyID");

                entity.HasOne(d => d.QuickReply)
                    .WithMany(p => p.QuickReplyKeyWords)
                    .HasForeignKey(d => d.QuickReplyId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_QuickReplyKeyWords_QuickReplies");
            });

            modelBuilder.Entity<Registration>(entity =>
            {
                entity.Property(e => e.ContestCategoryId).HasColumnName("Contest_CategoryID");

                entity.Property(e => e.MemberId).HasColumnName("MemberID");

                entity.HasOne(d => d.ContestCategory)
                    .WithMany(p => p.Registration)
                    .HasForeignKey(d => d.ContestCategoryId)
                    .HasConstraintName("FK_RegistrationForm_Contest_Category");
            });

            modelBuilder.Entity<RegistrationInformation>(entity =>
            {
                entity.ToTable("Registration_Information");

                entity.Property(e => e.InformationId).HasColumnName("InformationID");

                entity.Property(e => e.RegistrationId).HasColumnName("RegistrationID");

                entity.HasOne(d => d.Information)
                    .WithMany(p => p.RegistrationInformation)
                    .HasForeignKey(d => d.InformationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Registration_Information_Information");

                entity.HasOne(d => d.Registration)
                    .WithMany(p => p.RegistrationInformation)
                    .HasForeignKey(d => d.RegistrationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Registration_Information_Registration");
            });

            modelBuilder.Entity<Stocks>(entity =>
            {
                entity.Property(e => e.ProductId).HasColumnName("Product_Id");

                entity.Property(e => e.ProductSizeId).HasColumnName("ProductSize_Id");

                entity.HasOne(d => d.Product)
                    .WithMany(p => p.Stocks)
                    .HasForeignKey(d => d.ProductId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Stocks_Products");

                entity.HasOne(d => d.ProductSize)
                    .WithMany(p => p.Stocks)
                    .HasForeignKey(d => d.ProductSizeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Stocks_ProductSize");
            });

            modelBuilder.Entity<Suppliers>(entity =>
            {
                entity.HasKey(e => e.SupplierId);

                entity.Property(e => e.SupplierAdd)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.SupplierName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.SupplierTel)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

        public DbSet<The_fifth_group_FinalAPI.DTOs.Forum_FirstDTO> Forum_FirstDTO { get; set; }
    }
}